version: "3.8"
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - flask
  flask:
    build: ./flask
    command: gunicorn -b 0.0.0.0:5000 wsgi:app
    expose:
      - 5000
